# Generated by Django 4.1.12 on 2023-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ID', models.IntegerField(default=999, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default='Memingo', max_length=255)),
                ('Edad', models.IntegerField(default=19)),
                ('Ocupacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
    ]
