# Generated by Django 4.1.12 on 2023-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prediccion',
            fields=[
                ('fecha', models.DateField(default='2023/10/18')),
                ('lvlA', models.FloatField(default=0.5, max_length=100)),
                ('username', models.CharField(default='memin', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prediccion',
            },
        ),
    ]
